added std and variance
lab-cosmo/equistore pull request #113
Opened 2023-02-06 21:07 UTC by DavideTisi

I add this for the variance and the std over the samples. These are used in the Ridge regression.
For the values in the block it is straightforward, and it is already implemented. The problems are the derivatives. Also because I do not know how much can be used the true derivative of the variance:

`Grad[Var[X]] = 2(E[X Grad[X]] - E[X]E[Grad[X]])`
(for the variance it is actually implemented I have few remaining problems with the std.

what do you think?

2023-02-12 19:16 UTC, DavideTisi commented
it should pass the test but i think that they are quite difficult to understand.

2023-02-15 21:04 UTC, PicoCentauri requested changes
Nice @Davide. Maybe adding a unittest that tests if only one sample is present there is no error raised and we return either nan or 0.

Also didnt we said we want to raise a warning for gradients if there is only one sample?

2023-02-16 11:29 UTC, DavideTisi commented
> Nice @davide. Maybe adding a unittest that tests if only one sample is present there is no error raised and we return either NaN or 0.
> 
> Also didnt we said we want to raise a warning for gradients if there is only one sample?

So what happens now is that if there is only one sample variance e std are zero, (there is a test for that I will put a comment maybe). 
For the gradients: the gradient of the variance is correctly zero; the problems appear in the gradient of std which has a term at the denominator. Now "it raises a warning" if an element of std is zero, but is the standard "division by zero" warning of division of NumPy arrays. Maybe you meant something custom.

But more important I thought a bit more about that and the behaviour is wrong: 
As I said the code in the present state leaves numpy (or any underline system in which you store the arrays to handle the exception of division by zero). I think that numpy put a None for that element, but this is wrong in our case.

Suppose you have only one value to compute the std; then the std of one number is the function identically zero, which derivative is again the function identically zero, not matter of the formula that simply do not apply for that case. 

All this treatment is ok but it must also be considered that the derivative of std probably has not a big meaning and it is not super defined.

2023-02-16 11:29 UTC, DavideTisi commented
Conclusion yes we for sure have at leat to catch the error and replace that values with 0

2023-02-17 14:04 UTC, DavideTisi commented
Thanks, @PicoCentauri for the help.
The last commits should handle adequately the case with only one value for the std.
I added tests for that case.

2023-02-22 16:04 UTC, PicoCentauri approved these changes
Looks, good. I have some general comments that we can address after this PR.

2023-02-22 16:04 UTC, PicoCentauri commented on python/src/equistore/operations/reduce_over_samples.py
> +                (-1,) + (1,) * len(other_shape)
I like this trick :)

2023-02-22 16:04 UTC, PicoCentauri commented on python/src/equistore/operations/reduce_over_samples.py
> +    over the ``samples_names`` indices.
We can leave this for now, but should try to shorten the "short" description into a line.

2023-02-22 16:04 UTC, PicoCentauri commented on python/tests/operations/reduce_over_samples.py
> +        )
Also lets try to split this into individual tests in the future. This makes debugging in case of errors easier.

2023-02-22 16:05 UTC, merged