drop_blocks and tests
lab-cosmo/equistore pull request #179
Opened 2023-03-09 10:23 UTC by cbenmahm

fix #168

2023-03-09 10:33 UTC, jwa7 requested changes
Looking really good, thanks @cbenmahm ! Some changes requested, particular with creating a pytest fixture and a few minor things, but mostly there :)

2023-03-09 10:33 UTC, jwa7 commented on python/tests/operations/drop_blocks.py
> +
```suggestion
@pytest.fixture
def test_tensor_map() -> TensorMap:
    return equistore.io.load(
            os.path.join(DATA_ROOT, "qm7-power-spectrum.npz"),
            use_numpy=True,
        )
```

2023-03-09 10:33 UTC, jwa7 commented on python/tests/operations/drop_blocks.py
> +
Then for each function, add `test_tensor_map` as an argument. For instance:

```py
def drop_all(self, test_tensor_map):
    ...
```
and of course in the body of the functions the variable name should be changed from `tensor` to `test_tensor_map`.

2023-03-09 10:33 UTC, jwa7 commented on python/tests/operations/drop_blocks.py
> +        raise ValueError("the two tensors have different labels")
```suggestion
        raise ValueError("the two tensors have different key names")
```

2023-03-09 10:33 UTC, jwa7 commented on python/tests/operations/drop_blocks.py
> +            raise ValueError("tensor2 has values that are not present in tensor1")
```suggestion
            raise ValueError(f"the blocks indexed key {key} are not equivalent")
```

2023-03-09 10:33 UTC, jwa7 commented on python/tests/operations/drop_blocks.py
> +    # this test will fail for now because of issue #175
Nice thank you!

2023-03-09 10:35 UTC, jwa7 commented
Also, we currently have a build failure on the docs. From the top directory of equistore, where you would run `tox`, try running `tox -e docs` and observing the output to see what the problem might be. If you need help let me know :)

2023-03-09 12:43 UTC, jwa7 requested changes

2023-03-09 12:43 UTC, jwa7 commented on python/src/equistore/operations/drop_blocks.py
> +    #         raise ValueError(f"passed key {key} does not exist in `tensor`")
```suggestion
```
these commented out lines need to be removed

2023-03-09 12:43 UTC, jwa7 commented on python/tests/operations/drop_blocks.py
> +    def test_drop_all(self, test_tensor_map):
Some short docstrings on each test function describing what the test does would be useful

2023-03-10 10:42 UTC, Luthaf commented
Unrelated to this PR, but you can also add yourself to the [AUTHOR](https://github.com/lab-cosmo/equistore/blob/master/AUTHORS) file @cbenmahm!

2023-03-10 13:25 UTC, jwa7 approved these changes
Looks great, thanks @cbenmahm !

2023-03-10 13:27 UTC, merged

2023-03-10 13:35 UTC, Luthaf commented on python/tests/operations/drop_blocks.py
> +        with pytest.raises(ValueError, match=re.escape(error_msg)):
I don't think we need regex for this, since we are matching the full error message and not just part of it