from_array function
lab-cosmo/equistore pull request #241
Opened 2023-04-01 16:31 UTC by frostedoyster

2023-04-01 17:03 UTC, DavideTisi approved these changes

2023-04-03 08:19 UTC, Luthaf requested changes
This function needs to be added to the documentation

2023-04-03 08:19 UTC, Luthaf commented on python/src/equistore/operations/from_array.py
> +def from_array(array):
```suggestion
def block_from_array(array: equistore.data.Array) -> TensorBlock:
```

2023-04-03 11:06 UTC, PicoCentauri commented
Just as a reference I did a function for this in [equisolve](https://github.com/lab-cosmo/equisolve/blob/0da105f03d6f7f54f3bb105561b7709b7602fbd2/src/equisolve/numpy/utils.py#L44-L84). @frostedoyster you might take a look.

2023-04-04 13:34 UTC, Luthaf approved these changes

2023-04-04 13:34 UTC, merged