changing the arguments of slice()
lab-cosmo/equistore pull request #245
Opened 2023-04-03 11:43 UTC by cbenmahm

fix #144

2023-04-03 12:23 UTC, jwa7 requested changes
Looking mostly good thanks @cbenmahm ! Suggestions are mostly to do with the change of args to be mandatory, but also some docstrings need updating.

One more thing: it would be great if we could change the arg `grouped_idxs` in the `split.py` functions (and tests) to be `grouped_labels`, re: @Luthaf 's comment on the original issue #144 :)

2023-04-03 12:23 UTC, jwa7 commented on python/src/equistore/operations/slice.py
> +    elif axis == "properties":
```suggestion
    else:  # properties
```

2023-04-03 12:23 UTC, jwa7 commented on python/src/equistore/operations/slice.py
>      """
The docstring needs to be updated to the new args here

2023-04-03 12:23 UTC, jwa7 commented on python/src/equistore/operations/slice.py
> +    if axis == "samples" and labels is not None:
```suggestion
    if axis == "samples":
```

2023-04-03 15:57 UTC, Luthaf commented on python/src/equistore/operations/slice.py
> +            else:  # properties
```suggestion
            else:
                assert axis == "properties"
```

2023-04-04 13:18 UTC, jwa7 commented on python/src/equistore/operations/slice.py
> +    `axis`. dimension(s). ``labels`` is a
```suggestion
    `axis`.  `labels` is a
```

2023-04-04 13:18 UTC, jwa7 commented on python/src/equistore/operations/slice.py
```suggestion
```

2023-04-04 13:18 UTC, jwa7 commented on python/src/equistore/operations/slice.py
> +    `axis`. dimension(s). ``labels`` is
```suggestion
    `axis`. `labels` is
```

2023-04-04 13:18 UTC, jwa7 commented on python/src/equistore/operations/slice.py
```suggestion
```

2023-04-04 13:18 UTC, jwa7 commented on python/src/equistore/operations/slice.py
> +    else:  # properties
```suggestion
    else:
        assert axis == "properties"
```

2023-04-04 13:18 UTC, jwa7 commented on python/src/equistore/operations/slice.py
> +    else:  # properties
```suggestion
    else:
        assert axis == "properties"
```

2023-04-05 11:27 UTC, Luthaf reviewed
Please also update slice tests to use pytest, you are already changing most of them anyway

2023-04-05 11:27 UTC, Luthaf commented on python/tests/operations/join.py
> +    @pytest.fixture
why are these indented?

2023-04-05 12:10 UTC, jwa7 commented on python/tests/operations/join.py
> +    @pytest.fixture
Good spot, thanks! Fixed.

2023-04-05 12:12 UTC, jwa7 commented
Made some changes; fixed the indentation issue with the join tests, and changed the split arg from `grouped_idxs` to `grouped_labels`.

Still to do: port the slice tests to pytest

2023-04-06 11:19 UTC, jwa7 commented
Tests ported to PyTest by @cbenmahm . I made some minor changes, removing the test classes.

2023-04-06 12:51 UTC, Luthaf approved these changes

2023-04-06 12:53 UTC, merged